-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public."DimDate";

CREATE TABLE IF NOT EXISTS public."DimDate"
(
    "Dateid" bigint NOT NULL,
    "Date" date NOT NULL,
    "Day" integer NOT NULL,
    "Weekday" integer NOT NULL,
    "WeekdayName" character varying(10) NOT NULL,
    "Month" integer NOT NULL,
    "MonthName" character varying(10) NOT NULL,
    "Quarter" integer NOT NULL,
    "QuarterName" character varying(2) NOT NULL,
    "Year" integer NOT NULL,
    PRIMARY KEY ("Dateid")
);

DROP TABLE IF EXISTS public."DimCategory";

CREATE TABLE IF NOT EXISTS public."DimCategory"
(
    "Categoryid" bigint NOT NULL,
    "CategoryName" character varying(10) NOT NULL,
    PRIMARY KEY ("Categoryid")
);

DROP TABLE IF EXISTS public."DimItem";

CREATE TABLE IF NOT EXISTS public."DimItem"
(
    "Itemid" bigint NOT NULL,
    "ItemName" character varying(100) NOT NULL,
    PRIMARY KEY ("Itemid")
);

DROP TABLE IF EXISTS public."DimCountry";

CREATE TABLE IF NOT EXISTS public."DimCountry"
(
    "Countryid" integer NOT NULL,
    "CountryName" character varying(30) NOT NULL,
    PRIMARY KEY ("Countryid")
);

DROP TABLE IF EXISTS public."FactSales";

CREATE TABLE IF NOT EXISTS public."FactSales"
(
    "Orderid" bigint NOT NULL,
    "Amount" numeric(9, 2) NOT NULL,
    "Dateid" bigint NOT NULL,
    "Categoryid" bigint NOT NULL,
    "Countryid" bigint NOT NULL,
    "Itemid" bigint NOT NULL,
    PRIMARY KEY ("Orderid")
);

ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT order_date_fk FOREIGN KEY ("Dateid")
    REFERENCES public."DimDate" ("Dateid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT order_category_id FOREIGN KEY ("Categoryid")
    REFERENCES public."DimCategory" ("Categoryid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT order_item_ft FOREIGN KEY ("Itemid")
    REFERENCES public."DimItem" ("Itemid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactSales"
    ADD CONSTRAINT order_country_fk FOREIGN KEY ("Countryid")
    REFERENCES public."DimCountry" ("Countryid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;